# @name /ping
GET {{base_url}}/ping

###

# @name /summaries
GET {{base_url}}/summaries/

###

# @name /summaries
POST {{base_url}}/summaries/
Content-Type: application/json

{
    "url": "{{url}}"
}

###

# @name /summaries/{id}/
GET {{base_url}}/summaries/{{summary_id}}/
